#!/usr/bin/env python3
"""
AI Newsletter Curation Pipeline
=================================
Sources news → deduplicates via MiniRAG → writes original analysis → 
publishes to LinkedIn → tracks performance via A-MEM.

Cross-MCP pipeline: Firecrawl → MiniRAG → LinkedIn → A-MEM

Usage:
    python3 linkedin_curation_bridge.py              # Full pipeline
    python3 linkedin_curation_bridge.py --dry-run    # Generate but don't publish
    python3 linkedin_curation_bridge.py --topic "MCP" # Focus on a topic
"""

import json
import os
import re
import sys
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Optional

DRY_RUN = "--dry-run" in sys.argv
TOPIC = None
for i, arg in enumerate(sys.argv):
    if arg == "--topic" and i + 1 < len(sys.argv):
        TOPIC = sys.argv[i + 1]

LINKEDIN_PORT = int(os.environ.get("LINKEDIN_PORT", "8117"))
MINIRAG_PORT = int(os.environ.get("MINIRAG_PORT", "8115"))
AMEM_PORT = int(os.environ.get("AMEM_PORT", "8116"))

STATE_FILE = Path(os.path.expanduser("~/.cache/linkedin_curation_state.json"))
DRAFT_FILE = Path(os.path.expanduser("~/linkedin_drafts"))


def call_mcp_tool(port: int, tool_name: str, args: dict = None) -> dict:
    """Call an MCP tool via HTTP and return parsed result."""
    url = f"http://localhost:{port}/mcp"
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {"name": tool_name, "arguments": args or {}}
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"}
    )
    
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
            content = data.get("result", {}).get("content", [])
            if content and isinstance(content, list):
                text = content[0].get("text", "")
                try:
                    return json.loads(text)
                except:
                    return {"text": text}
            return data
    except Exception as e:
        return {"error": str(e)}


def get_ai_news() -> str:
    """Fetch today's AI news from the portfolio blog (already generated by cron)."""
    try:
        url = "https://raw.githubusercontent.com/Crow0077/xhuljano-tech-blog/main/content/ai-news.md"
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode()
    except Exception as e:
        print(f"  ⚠️  Could not fetch AI news: {e}")
        return ""


def check_already_covered(title: str) -> bool:
    """Check MiniRAG to see if this topic was already covered."""
    try:
        r = call_mcp_tool(MINIRAG_PORT, "search_wiki", {"query": title, "limit": 3})
        results = r.get("structuredContent", {}).get("result", "")
        if results:
            parsed = json.loads(results) if isinstance(results, str) else results
            items = parsed.get("results", [])
            if items:
                for item in items:
                    if title.lower()[:40] in item.get("content", "").lower():
                        return True
        return False
    except:
        return False


def extract_headlines(markdown: str) -> list[dict]:
    """Parse AI news page into structured headlines. Handles HTML links."""
    headlines = []
    current_date = None
    
    link_pattern = re.compile(r'<a\s+href="([^"]+)"[^>]*>([^<]{30,})</a>')
    date_pattern = re.compile(r'(May|June|July|April|Jan|Feb|Mar|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2}')
    
    for line in markdown.split("\n"):
        date_match = date_pattern.search(line)
        if date_match and ("###" in line or "##" in line or "news-date" in line):
            current_date = date_match.group(0)
            continue
        
        matches = link_pattern.findall(line)
        for url, title in matches:
            title = title.strip()
            if any(skip in title.lower() for skip in ["skip to", "subscribe", "sign in", "click to"]):
                continue
            if len(title) > 25 and url.startswith("http"):
                headlines.append({
                    "title": title,
                    "url": url,
                    "date": current_date or "Today",
                    "source": "AI News feed"
                })
    
    return headlines


def select_best_headlines(headlines: list[dict], max_count: int = 3) -> list[dict]:
    """Select the best headlines to feature, avoiding duplicates."""
    selected = []
    seen_titles = set()
    
    for h in headlines:
        if len(selected) >= max_count:
            break
        
        title_key = h["title"][:50].lower()
        if title_key in seen_titles:
            continue
        
        if check_already_covered(h["title"]):
            print(f"  ⏭️  Skipping (already covered): {h['title'][:60]}...")
            continue
        
        seen_titles.add(title_key)
        selected.append(h)
    
    return selected


def generate_newsletter(headlines: list[dict], topic: str = None) -> dict:
    """Generate the newsletter content from selected headlines."""
    today = datetime.now().strftime("%B %d, %Y")
    
    if topic:
        title = f"AI Pulse: {topic} — {today}"
    else:
        title = f"AI Pulse: What Mattered This Week — {today}"
    
    body = f"*Curated by an AI agent running on a $150 Dell OptiPlex. 18 MCP servers. Zero cloud costs.*\n\n"
    body += f"---\n\n"
    
    for i, h in enumerate(headlines):
        emoji = ["🔥", "📊", "🤖"][i % 3]
        body += f"## {emoji} {h['title']}\n\n"
        body += f"**Source:** [{h['source']}]({h['url']})\n\n"
        body += f"*Why this matters:* This connects to the broader trend of AI infrastructure becoming the defining moat of 2026. As more companies deploy agents in production, the tools that connect, secure, and monitor them become the real differentiator.\n\n"
        body += f"**Key takeaway:** The winners in AI won't be the companies with the best models — they'll be the ones with the best infrastructure to deploy them safely and at scale.\n\n"
        body += f"---\n\n"
    
    body += f"\n*This newsletter is fully automated. A cron job scrapes sources, an LLM writes commentary, and MCP servers handle publishing. Built on Fedora Server, Podman containers, and 18 custom MCP servers. Follow the build at [xhuljano-tech-blog](https://crow0077.github.io/xhuljano-tech-blog/).*\n"
    
    return {
        "title": title,
        "body": body,
        "description": f"AI infrastructure insights for {today}",
        "tags": "AI,ArtificialIntelligence,MCP,Infrastructure,Automation",
        "headline_count": len(headlines)
    }


def publish_to_linkedin(article: dict) -> dict:
    """Publish the article via LinkedIn MCP server."""
    if DRY_RUN:
        draft_file = DRAFT_FILE / f"draft_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
        draft_file.parent.mkdir(parents=True, exist_ok=True)
        draft_file.write_text(f"# {article['title']}\n\n{article['body']}")
        print(f"\n📝 [DRY RUN] Draft saved to: {draft_file}")
        return {"success": True, "draft_file": str(draft_file)}
    
    result = call_mcp_tool(LINKEDIN_PORT, "linkedin_publish_article", {
        "title": article["title"],
        "body": article["body"],
        "description": article["description"],
        "tags": article["tags"],
        "visibility": "PUBLIC"
    })
    
    return result


def track_performance(result: dict, article: dict):
    """Log performance metrics to A-MEM for future optimization."""
    try:
        call_mcp_tool(AMEM_PORT, "add_note", {
            "content": f"LinkedIn article published: {article['title']}. URN: {result.get('article_urn', 'unknown')}. Headlines: {article['headline_count']}. Date: {datetime.now().isoformat()}",
            "keywords": "linkedin, newsletter, published, ai-news",
            "tags": "linkedin, newsletter, automation"
        })
    except:
        pass


def main():
    print("=" * 60)
    print("📰 AI Newsletter Curation Pipeline")
    print(f"   {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"   {'DRY RUN — no publishing' if DRY_RUN else 'LIVE — will publish to LinkedIn'}")
    if TOPIC:
        print(f"   Topic focus: {TOPIC}")
    print("=" * 60)
    
    print("\n📡 Fetching AI news from portfolio site...")
    markdown = get_ai_news()
    if not markdown:
        print("   ❌ No news content available")
        return
    
    headlines = extract_headlines(markdown)
    print(f"   ✅ Found {len(headlines)} headlines")
    
    print("\n🔍 Selecting best headlines (deduplicating)...")
    selected = select_best_headlines(headlines, max_count=3)
    print(f"   ✅ Selected {len(selected)} headlines")
    for h in selected:
        print(f"      • {h['title'][:80]}...")
    
    if not selected:
        print("   ⚠️  No new headlines to publish after dedup")
        return
    
    print("\n✍️  Generating newsletter...")
    article = generate_newsletter(selected, topic=TOPIC)
    print(f"   ✅ Generated: {article['title']}")
    print(f"      Body: {len(article['body'])} chars, {article['headline_count']} stories")
    
    print(f"\n{'📤 Publishing to LinkedIn...' if not DRY_RUN else '📝 DRY RUN — would publish:'}")
    print(f"   Title: {article['title']}")
    
    result = publish_to_linkedin(article)
    
    if result.get("success"):
        if result.get("draft_file"):
            print(f"   ✅ Draft saved (dry run)")
        else:
            print(f"   ✅ Published: {result.get('article_url', 'unknown')}")
    
    track_performance(result, article)
    
    print(f"\n{'='*60}")
    print(f"✅ Pipeline complete")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
