#!/usr/bin/env python3
"""
Sentinel → GitHub Issues Bridge
================================
Runs sentinel_full_audit, parses findings, creates grouped GitHub issues.
One issue per affected file with all findings listed.
Deduplicates by file+pattern hash to avoid re-opening fixed issues.

Usage:
    python3 sentinel_github_bridge.py          # Run audit, create issues
    python3 sentinel_github_bridge.py --dry-run # Parse only, no GitHub writes
"""

import json
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path
from datetime import datetime

DRY_RUN = "--dry-run" in sys.argv
REPO_OWNER = "Crow0077"
REPO_NAME = "homelab-ai-toolkit"
SENTINEL_PORT = 8113
STATE_FILE = Path(os.path.expanduser("~/.cache/sentinel_issues.json"))


def call_mcp_tool(port: int, tool_name: str, args: dict = None) -> str:
    """Call an MCP tool via HTTP and return the text result."""
    import urllib.request
    url = f"http://localhost:{port}/mcp"
    
    payload = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {
            "name": tool_name,
            "arguments": args or {}
        }
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"}
    )
    
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read())
            content = data.get("result", {}).get("content", [])
            if content and isinstance(content, list):
                return content[0].get("text", "")
            return json.dumps(data)
    except Exception as e:
        return f"ERROR: {e}"


def parse_findings(audit_text: str) -> list[dict]:
    """Parse sentinel audit output into structured findings."""
    findings = []
    current_file = None
    current_section = None
    
    for line in audit_text.split("\n"):
        if "HERMES CONFIG" in line:
            current_section = "config"
            continue
        elif "SERVER CODE" in line:
            current_section = "code"
            continue
        elif "SUPPLY CHAIN" in line:
            current_section = "supply"
            continue
        elif "PROMPT INJECTION" in line:
            current_section = "prompt"
            continue
        
        if "🔴" in line or "🟠" in line or "🟡" in line:
            severity = "critical" if "🔴" in line else ("high" if "🟠" in line else "medium")
            
            file_match = re.search(r'(\w+\.py|\w+\.md|server\.py)', line)
            if file_match:
                current_file = file_match.group(1)
            
            pattern = line.split("[")[1].split("]")[0] if "[" in line and "]" in line else "unknown"
            
            findings.append({
                "file": current_file or "unknown",
                "severity": severity,
                "pattern": pattern.strip(),
                "raw_line": line.strip(),
                "section": current_section or "unknown"
            })
    
    return findings


def group_by_file(findings: list[dict]) -> dict[str, list[dict]]:
    """Group findings by file, deduplicate by pattern."""
    grouped = {}
    for f in findings:
        key = f["file"]
        if key not in grouped:
            grouped[key] = []
        if not any(existing["pattern"] == f["pattern"] for existing in grouped[key]):
            grouped[key].append(f)
    return grouped


def build_issue_body(file: str, findings: list[dict]) -> str:
    """Build a GitHub issue body from grouped findings."""
    crit = [f for f in findings if f["severity"] == "critical"]
    high = [f for f in findings if f["severity"] == "high"]
    medium = [f for f in findings if f["severity"] == "medium"]
    
    body = f"## Sentinel Security Audit — {file}\n\n"
    body += f"**Scan date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
    body += f"**Findings:** {len(crit)} critical, {len(high)} high, {len(medium)} medium\n\n"
    body += "### Findings\n\n"
    
    all_findings = crit + high + medium
    for f in all_findings:
        emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡"}[f["severity"]]
        body += f"- {emoji} **[{f['severity'].upper()}]** {f['pattern']}\n"
        body += f"  Section: {f['section']}\n\n"
    
    body += "---\n"
    body += "*Auto-generated by Sentinel → GitHub Issues Bridge. Review and fix, then close this issue.*\n"
    
    return body


def load_state() -> dict:
    """Load previously filed issues to avoid duplicates."""
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except:
            pass
    return {}


def save_state(state: dict):
    """Save filed issue state."""
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


def create_github_issue(title: str, body: str, labels: list[str]) -> bool:
    """Create a GitHub issue via gh CLI. Returns True if created."""
    if DRY_RUN:
        print(f"  [DRY RUN] Would create: {title}")
        return True
    
    try:
        labels_arg = ",".join(labels)
        cmd = [
            "gh", "issue", "create",
            "--repo", f"{REPO_OWNER}/{REPO_NAME}",
            "--title", title,
            "--body", body,
            "--label", labels_arg
        ]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if r.returncode == 0:
            print(f"  ✅ Created: {r.stdout.strip()}")
            return True
        else:
            print(f"  ❌ Failed: {r.stderr.strip()}")
            return False
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False


def main():
    print("🔍 Running Sentinel Full Audit...")
    audit_text = call_mcp_tool(SENTINEL_PORT, "sentinel_full_audit")
    
    if audit_text.startswith("ERROR"):
        print(f"❌ Failed to run audit: {audit_text}")
        sys.exit(1)
    
    print("📊 Parsing findings...")
    findings = parse_findings(audit_text)
    print(f"   Found {len(findings)} raw findings")
    
    grouped = group_by_file(findings)
    print(f"   Grouped into {len(grouped)} files")
    
    state = load_state()
    
    issues_created = 0
    issues_skipped = 0
    
    for file, file_findings in sorted(grouped.items()):
        crit_count = len([f for f in file_findings if f["severity"] == "critical"])
        high_count = len([f for f in file_findings if f["severity"] == "high"])
        
        fingerprint = hashlib.md5(
            json.dumps([f["pattern"] for f in file_findings], sort_keys=True).encode()
        ).hexdigest()
        
        if state.get(file) == fingerprint:
            issues_skipped += 1
            continue
        
        title = f"🔐 Security: {file} — {crit_count} critical, {high_count} high (Sentinel Audit)"
        body = build_issue_body(file, file_findings)
        labels = ["security", "sentinel-audit"]
        
        print(f"\n📝 {file}: {crit_count} crit, {high_count} high, {len(file_findings) - crit_count - high_count} medium")
        
        if create_github_issue(title, body, labels):
            state[file] = fingerprint
            issues_created += 1
    
    save_state(state)
    
    print(f"\n{'='*50}")
    print(f"✅ Done: {issues_created} issues created, {issues_skipped} skipped (unchanged)")
    print(f"   State saved to {STATE_FILE}")


if __name__ == "__main__":
    main()
